pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'Pay-As-You-Go'
    ScriptPath: 'https://github.com/HardikGajjar-alept/CICDBluePrints/blob/master/pipelines-scripts/build.ps1'
    ScriptArguments: -ResourceGroupName 'demogroup' -ResourceGroupLocation 'centralus' -UploadArtifacts -ArtifactStagingDirectory '$(Build.StagingDirectory)' -StorageAccountName 'stage3a4176e058d34bb88cc'
    azurePowerShellVersion: LatestVersion