steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'CICD'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CICD'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'blueprint'
    deploymentMode: 'Incremental'