steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Pay-As-You-Go'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CICD'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-storage-account-create/azuredeploy.json'
    deploymentMode: 'Incremental'